### ISSUE TITLE
Connection name not used

### ISSUE THREAD

**Issue by CaptainKant** [krlove/eloquent-model-generator#18] opened 2017-03-11 15:21 UTC
Hi, thanks for this vendor,
The option --connection seems to not be used in processors however

```
$this->databaseManager->connection()  //instead of 
$this->databaseManager->connection($someConfigValue)

```
So only the main database can be directly worked on it

**Comment by krlove** [comment] 2017-03-19 12:24
Hi @CaptainKant,

thanks for your contribution, the issue is fixed in version 1.2.3 in this [commit](https://github.com/krlove/eloquent-model-generator/commit/0bfc62432cddc4f9f800f8c81bb159e57e66ca17)

**Closed** 2017-04-05 12:05 UTC
